# ================= ???? =================

# ???????trace < debug < info < warn < error < off
level = info

# ????????????? (?????????? false)
level@com.example.MyTestClass = trace


# ================= ??? Writer (Console) =================

# ??????? (???? true????)
writer.console = true

# ??????
# ?????:
# {date}: ???? (?????? {date: yyyy-MM-dd HH:mm:ss})
# {level}: ????
# {class}: ????
# {class-name}: ????
# {method}: ???
# {line}: ?? (??????)
# {thread}: ???
# {message}: ????
# {exception}: ????
writer.console.format = [{date: yyyy-MM-dd}/{date: HH:mm:ss}][{class}/{level}]:{message} {exception}

# ?????????
writer.console.level = info

# ????
# auto: ????????/?? (??)
# true: ???? ANSI ????
# false: ???????
writer.console.color = true

# ???
# system.out: ???? (????????)
# system.err: ???? (???? error/warn?????)
writer.console.output = system.err


# ================= ?? Writer (File) - ???????? =================
# ????????????????? writer.file????? false

# writer.file = true
# writer.file.file = logs/app.log
# writer.file.format = {date: yyyy-MM-dd HH:mm:ss} [{level}] {class}: {message}{exception}
# writer.file.level = info
# writer.file.policies = startup, daily: 02:00
# writer.file.retainer = days: 7